# Specify the line length that the printer will wrap on.
printWidth: 100
# Specify the number of spaces per indentation-level.
tabWidth: 2
# Indent lines with tabs instead of spaces.
useTabs: false
# Print semicolons at the ends of statements.
semi: true
# Use single quotes instead of double quotes.
singleQuote: true
# Change when properties in objects are quoted.
# as-needed: Only add quotes around object properties where required.
quoteProps: 'as-needed'
# Use single quotes instead of double quotes in JSX.
jsxSingleQuote: true
# Print trailing commas wherever possible in multi-line comma-separated syntactic structures.
# (A single-line array, for example, never gets trailing commas.)
trailingComma: 'all'
# Print spaces between brackets in object literals.
# true: Example: { foo: bar }.
bracketSpacing: true
# Put the > of a multi-line HTML (HTML, JSX, Vue, Angular) element at the end of
# the last line instead of being alone on the next line (does not apply to self closing elements).
bracketSameLine: false
# Include parentheses around a sole arrow function parameter.
# avoid: Omit parens when possible. Example: x => x
arrowParens: avoid
